import type { Metadata } from "next";
import { Roboto_Serif } from "next/font/google";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ResponsivNav from "@/components/Home/Navbar/ResponsivNav";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const font = Roboto_Serif({ 
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ["latin"] 
}); 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className}  antialiased`}
      >
        <ResponsivNav/>
      
        {children}
      </body>
    </html>
  );
}
